export const SUPERVISOR_ERROR_CODES = Object.freeze({
  STARTUP_NOT_READY: "STARTUP_NOT_READY",
  DRAIN_INCOMPLETE: "DRAIN_INCOMPLETE",
  RESTART_NOT_READY: "RESTART_NOT_READY",
  RESTART_CIRCUIT_OPEN: "RESTART_CIRCUIT_OPEN",
});
