export const AUTH_ERROR_CODES = Object.freeze({
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_REFRESH_INVALID: "AUTH_REFRESH_INVALID",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_RECOVERY_FAILED: "AUTH_RECOVERY_FAILED",
  AUTH_RECOVERY_TIMEOUT: "AUTH_RECOVERY_TIMEOUT",
  AUTH_FALLBACK_TOKEN_MISSING: "AUTH_FALLBACK_TOKEN_MISSING",
  WORKER_UNAVAILABLE: "WORKER_UNAVAILABLE",
  WORKER_LAUNCH_FAILED: "WORKER_LAUNCH_FAILED",
  WORKER_TOKEN_MISSING: "WORKER_TOKEN_MISSING",
  WORKER_FAILED: "WORKER_FAILED",
  WORKER_TIMEOUT: "WORKER_TIMEOUT",
});
